update readme for api updating and server setup
PDFTron/webviewer-BIM-sample pull request #1
Opened 2022-09-20 19:57 UTC by JingyeHou

## Overview
- This pr is for updating the renaming APIS such as **loadAsset** to **load3dAsset** and **initialize3dViewer** to **initializeBimViewer**. 
- Also the changes contain the instruction for server setup

##Test
Just go through the Readme file to see changes 

AEC-339

2022-09-22 18:35 UTC, AdamInTheOculus requested changes
Looks really good! A few minor comments.

2022-09-22 18:35 UTC, AdamInTheOculus commented on README.md
> +The server is supported on Windows, MacOs Intel(not supported for M1) and Linux.
```suggestion
The server is supported on Windows, Linux and MacOS Intel (M1 not supported).
```

2022-09-22 18:35 UTC, AdamInTheOculus commented on SERVER_README.md
> +This server comes packaged as either a binary or a Docker image available for Linux, MacOS Intel (not in M1) or Windows.
```suggestion
This server comes packaged as either a binary or a Docker image available for Windows, Linux and MacOS Intel (M1 not supported).
```

2022-09-22 18:35 UTC, AdamInTheOculus commented on SERVER_README.md
> +`docker run -p 8085:8085 -v {absolute_path_to_config.json}:/home/docjob/config 448036597521.dkr.ecr.us-east-1.amazonaws.com/docjob-3d:latest`
Can we confirm if we need the `448036597521.dkr.ecr.us-east-1.amazonaws.com/`? You _should_ be able to use just `docjob-3d:latest`.

2022-09-22 18:35 UTC, AdamInTheOculus commented on SERVER_README.md
> +`docker run -p 8085:8085 -e trn_license="my_license_key" 448036597521.dkr.ecr.us-east-1.amazonaws.com/docjob-3d:latest`
Same as above. Can you confirm if we need the `448036597521.dkr.ecr.us-east-1.amazonaws.com/` prefix?

2022-09-26 17:01 UTC, JingyeHou commented on SERVER_README.md
> +`docker run -p 8085:8085 -v {absolute_path_to_config.json}:/home/docjob/config 448036597521.dkr.ecr.us-east-1.amazonaws.com/docjob-3d:latest`
Yes, I confirmed with Ramzi that using `448036597521.dkr.ecr.us-east-1.amazonaws.com/docjob-3d:latest` instead of just using `docjob-3d:latest`

2022-09-26 17:02 UTC, JingyeHou commented on SERVER_README.md
> +`docker run -p 8085:8085 -e trn_license="my_license_key" 448036597521.dkr.ecr.us-east-1.amazonaws.com/docjob-3d:latest`
I confirmed with Ramzi for the prefix!!

2022-09-29 17:09 UTC, AdamInTheOculus approved these changes
LGTM! Great work, Jack! 🙏

2022-09-29 21:36 UTC, merged